# Generated by Django 3.1.5 on 2021-02-28 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cet', '0003_auto_20210227_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtransactions',
            name='registered_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pending_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
